spring:
  config:
    import: optional:file:.env[.properties]  #스프링 .env를 자동으로 읽지 않음 읽을 수 있도록 설정 추가
  mustache:
    servlet:
      expose-session-attributes: true  # 머스태치 파일에서 세션에 담을 값을 바로 사용 가능
  profiles:
    active: local